spring:
    application:
        name: GatewayService

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9091/eureka

server:
    port: 8084

zuul:
    routes:
        employeeDashboard:
            serviceId: EmployeeDashboard
    
    host:
        socket-timeout-millis: 30000
